<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>


In [13]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [14]:
filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv"
df = pd.read_csv(filepath)
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

### Data Preprocessing


#### One Hot Encoding


In [15]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

First, we need to perform one hot encoding to convert categorical variables to binary variables.


In [16]:
df_sydney_processed.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0             41   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7             41   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1             41   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0             41   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0             41   

   WindSpeed9am  WindSpeed3pm  Humidity9am  ...  WindDir3pm_NNW  \
0            17            20           92  ...               0   
1             9            13           83  ...               0   
2            17             2           88  ...               0   
3            22            20           83  ...               0   
4            11             6           88  ...               0   

   WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_SSW  \
0              0             0              0               0               1   
1              0             0              0               0               0   
2              0             0              0               0               0   
3              0             0              0               0               0   
4              0             0              0               0               0   

   WindDir3pm_SW WindDir3pm_W  WindDir3pm_WNW  WindDir3pm_WSW  
0              0            0               0               0  
1              0            0               0               0  
2              0            0               0               0  
3              0            0               0               0  
4              0            1               0               0  

[5 rows x 68 columns]

Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [17]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [18]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [19]:
df_sydney_processed = df_sydney_processed.astype(float)

In [20]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

### Linear Regression


#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [23]:
x_train, x_test, y_train, y_test =  train_test_split(features,Y, test_size=0.2, random_state=10)

#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [24]:
LinearReg = LinearRegression()
LinearReg.fit(x_train,y_train)

LinearRegression()

#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [25]:
predictions = LinearReg.predict(x_test)

#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [26]:
LinearRegression_MAE = mean_absolute_error(y_test,predictions)
LinearRegression_MSE =mean_squared_error(y_test,predictions)
LinearRegression_R2 = r2_score(y_test,predictions)

#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [27]:
Report = {'MAE':LinearRegression_MAE,'MSE':LinearRegression_MSE,'R^2':LinearRegression_R2}
df = pd.DataFrame.from_dict(Report, orient='index', columns=['Value'])

df.reset_index(inplace=True)
df.rename(columns={'index': 'Metric'}, inplace=True)

print(df)

  Metric     Value
0    MAE  0.256317
1    MSE  0.115721
2    R^2  0.427132


### KNN


#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.


In [28]:
KNN = KNeighborsClassifier(n_neighbors = 4).fit(x_train,y_train)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [29]:
predictions = KNN.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [31]:
KNN_Accuracy_Score = accuracy_score(y_test,predictions)
KNN_JaccardIndex = jaccard_score(y_test,predictions)
KNN_F1_Score = f1_score(y_test,predictions)
print(KNN_Accuracy_Score)
print(KNN_JaccardIndex)
print(KNN_F1_Score)

0.8183206106870229
0.4251207729468599
0.5966101694915255


### Decision Tree


#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [32]:
Tree = DecisionTreeClassifier()
Tree.fit(x_train, y_train)

DecisionTreeClassifier()

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [33]:
predictions = Tree.predict(x_test)

#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [34]:
Tree_Accuracy_Score = accuracy_score(y_test,predictions)
Tree_JaccardIndex = jaccard_score(y_test,predictions)
Tree_F1_Score = f1_score(y_test,predictions)
print(Tree_Accuracy_Score)
print(Tree_JaccardIndex)
print(Tree_F1_Score)

0.7557251908396947
0.39849624060150374
0.5698924731182795


### Logistic Regression


#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [46]:
x_train, x_test, y_train, y_test = train_test_split(features,Y, test_size=0.2, random_state=1)

#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [47]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

#### Q14) Now, use the `predict` and `predict_proba` methods on the testing data (`x_test`) and save it as 2 arrays `predictions` and `predict_proba`.


In [48]:
predictions = LR.predict(x_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

In [49]:
predict_proba = LR.predict_proba(x_test)
predict_proba[0:5]

array([[0.71865806, 0.28134194],
       [0.97588275, 0.02411725],
       [0.49701229, 0.50298771],
       [0.66413194, 0.33586806],
       [0.97404704, 0.02595296]])

#### Q15) Using the `predictions`, `predict_proba` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [50]:
LR_Accuracy_Score = accuracy_score(y_test,predictions)
LR_JaccardIndex = jaccard_score(y_test,predictions)
LR_F1_Score = f1_score(y_test,predictions)
#only in Logistic Regression Model
LR_Log_Loss = log_loss(y_test,predict_proba)
print(LR_Accuracy_Score)
print(LR_JaccardIndex)
print(LR_F1_Score)
print(LR_Log_Loss)

0.8274809160305343
0.4840182648401826
0.6523076923076923
0.38008471302376406


### SVM


#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [40]:
SVM = svm.SVC(kernel='rbf')
SVM.fit(x_train, y_train)

SVC()

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [41]:
predictions = SVM.predict(x_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [42]:
SVM_Accuracy_Score = accuracy_score(y_test,predictions)
SVM_JaccardIndex = jaccard_score(y_test,predictions)
SVM_F1_Score = f1_score(y_test,predictions)
print(SVM_Accuracy_Score)
print(SVM_JaccardIndex)
print(SVM_F1_Score)

0.7221374045801526
0.0
0.0


### Report


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [44]:
Report1 = { 'KNN': {'Accuracy':KNN_Accuracy_Score,'Jaccard Index':KNN_JaccardIndex,'F1-Score':KNN_F1_Score},
          'Decision Tree': {'Accuracy':Tree_Accuracy_Score,'Jaccard Index':Tree_JaccardIndex,'F1-Score':Tree_F1_Score},
    'Logistic Regression':{'Accuracy':LR_Accuracy_Score,'Jaccard Index':KNN_JaccardIndex,'F1-Score':KNN_F1_Score,'LogLoss':LR_Log_Loss},
    'SVM': {'Accuracy':SVM_Accuracy_Score,'Jaccard Index':SVM_JaccardIndex,'F1-Score':SVM_F1_Score}
}
df = pd.DataFrame.from_dict(Report1, orient='index')

df.reset_index(inplace=True)
df.rename(columns={'index': 'ML Model'}, inplace=True)

print(df,'\n')
print(Report1)


              ML Model  Accuracy  Jaccard Index  F1-Score   LogLoss
0                  KNN  0.818321       0.425121  0.596610       NaN
1        Decision Tree  0.755725       0.398496  0.569892       NaN
2  Logistic Regression  0.827481       0.425121  0.596610  0.380085
3                  SVM  0.722137       0.000000  0.000000       NaN 

{'KNN': {'Accuracy': 0.8183206106870229, 'Jaccard Index': 0.4251207729468599, 'F1-Score': 0.5966101694915255}, 'Decision Tree': {'Accuracy': 0.7557251908396947, 'Jaccard Index': 0.39849624060150374, 'F1-Score': 0.5698924731182795}, 'Logistic Regression': {'Accuracy': 0.8274809160305343, 'Jaccard Index': 0.4251207729468599, 'F1-Score': 0.5966101694915255, 'LogLoss': 0.38008471302376406}, 'SVM': {'Accuracy': 0.7221374045801526, 'Jaccard Index': 0.0, 'F1-Score': 0.0}}
